// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.google.analytics.containertag.common;


public final class Key extends Enum
{

    private static final Key $VALUES[];
    public static final Key ACCOUNT;
    public static final Key ACTIVITY;
    public static final Key ADDITIONAL_PARAMS;
    public static final Key ADVERTISER;
    public static final Key ALGORITHM;
    public static final Key ALLOW_ANCHOR;
    public static final Key ALLOW_HASH;
    public static final Key ALLOW_LINKER;
    public static final Key ANALYTICS_FIELDS;
    public static final Key ANALYTICS_PASS_THROUGH;
    public static final Key ANONYMIZE_IP;
    public static final Key APP_NAME;
    public static final Key APP_VERSION;
    public static final Key ARG0;
    public static final Key ARG1;
    public static final Key ATTRIBUTE;
    public static final Key AUTO_LINK_DOMAINS;
    public static final Key CACHE_BUSTER;
    public static final Key CACHE_BUSTER_VALUE;
    public static final Key CAMPAIGN_CONTENT_KEY;
    public static final Key CAMPAIGN_CONTENT_OVERRIDE;
    public static final Key CAMPAIGN_COOKIE_TIMEOUT;
    public static final Key CAMPAIGN_MEDIUM_KEY;
    public static final Key CAMPAIGN_MEDIUM_OVERRIDE;
    public static final Key CAMPAIGN_NAME_KEY;
    public static final Key CAMPAIGN_NAME_OVERRIDE;
    public static final Key CAMPAIGN_NO_KEY;
    public static final Key CAMPAIGN_SOURCE_KEY;
    public static final Key CAMPAIGN_SOURCE_OVERRIDE;
    public static final Key CAMPAIGN_TERM_KEY;
    public static final Key CAMPAIGN_TERM_OVERRIDE;
    public static final Key CAMPAIGN_TRACK;
    public static final Key CATEGORY;
    public static final Key CHECK_VALIDATION;
    public static final Key CLEAR_PERSISTENT_DATA_LAYER_PREFIX;
    public static final Key CLICK_ID;
    public static final Key CLIENT_INFO;
    public static final Key COMPANY;
    public static final Key COMPONENT;
    public static final Key CONTENT_DESCRIPTION;
    public static final Key CONTENT_GROUP;
    public static final Key CONVERSION_ID;
    public static final Key COOKIE_DOMAIN;
    public static final Key COOKIE_EXPIRATION;
    public static final Key COOKIE_NAME;
    public static final Key COOKIE_PATH;
    public static final Key COOKIE_PATH_COPY;
    public static final Key COUNTRY;
    public static final Key CURRENCY_CODE;
    public static final Key CUSTOMER_ID;
    public static final Key CUSTOM_VARS;
    public static final Key DATA_LAYER_VERSION;
    public static final Key DATA_PROVIDER_ID;
    public static final Key DEBUG;
    public static final Key DECORATE_FORM;
    public static final Key DECORATE_FORMS_AUTO_LINK;
    public static final Key DECORATE_LINK;
    public static final Key DEFAULT_PAGES;
    public static final Key DEFAULT_VALUE;
    public static final Key DEPENDENCIES;
    public static final Key DETECT_FLASH;
    public static final Key DETECT_TITLE;
    public static final Key DIMENSION;
    public static final Key DOMAIN_NAME;
    public static final Key DOUBLE_CLICK;
    public static final Key ECOMMERCE_MACRO_DATA;
    public static final Key ECOMMERCE_USE_DATA_LAYER;
    public static final Key ELEMENT;
    public static final Key EMAIL;
    public static final Key EMPLOYEE_RANGE;
    public static final Key ENABLE_ECOMMERCE;
    public static final Key ESCAPE;
    public static final Key EVENT_ACTION;
    public static final Key EVENT_CATEGORY;
    public static final Key EVENT_LABEL;
    public static final Key EVENT_VALUE;
    public static final Key EXCEPTION_DESCRIPTION;
    public static final Key EXCEPTION_FATAL;
    public static final Key FIELDS_TO_SET;
    public static final Key FORCE_SSL;
    public static final Key FORM_OBJECT;
    public static final Key FUNCTION;
    public static final Key FUNCTION_CALL_NAME;
    public static final Key GROUP;
    public static final Key GTM_ON_FAILURE;
    public static final Key GTM_ON_SUCCESS;
    public static final Key HIT_CALLBACK;
    public static final Key HTML;
    public static final Key ID;
    public static final Key IGNORED_ORGANIC;
    public static final Key IGNORED_REF;
    public static final Key IGNORE_CASE;
    public static final Key INPUT;
    public static final Key INPUT_FORMAT;
    public static final Key INSTANCE_LABEL;
    public static final Key INSTANCE_NAME;
    public static final Key INTERVAL;
    public static final Key ITEM_SEPARATOR;
    public static final Key JAVASCRIPT;
    public static final Key KEYWORD;
    public static final Key KEY_VALUE_SEPARATOR;
    public static final Key LABEL;
    public static final Key LANGUAGE;
    public static final Key LIMIT;
    public static final Key LINK;
    public static final Key LINK_BY_POST;
    public static final Key LINK_ID;
    public static final Key LIVE_ONLY;
    public static final Key LOCAL_GIF_PATH;
    public static final Key LOCATION;
    public static final Key MAP;
    public static final Key MAX;
    public static final Key METRIC;
    public static final Key MIN;
    public static final Key NAME;
    public static final Key NAMESPACE_CODE;
    public static final Key NAMESPACE_ID;
    public static final Key NAMESPACE_VALUE;
    public static final Key NONINTERACTION;
    public static final Key NOT_DEFAULT_MACRO;
    public static final Key NO_PADDING;
    public static final Key NUMBER;
    public static final Key OPTOUT;
    public static final Key ORDER;
    public static final Key ORDER_ID;
    public static final Key ORDER_VALUE;
    public static final Key ORDINAL;
    public static final Key ORGANIC;
    public static final Key OUTPUT_FORMAT;
    public static final Key PAGE;
    public static final Key PAGE_PATH;
    public static final Key PARTITION;
    public static final Key PIXEL;
    public static final Key PLATFORM;
    public static final Key PRICES;
    public static final Key PRIORITY;
    public static final Key PRODUCT;
    public static final Key PRODUCT_ID;
    public static final Key PRODUCT_IDS;
    public static final Key PUSH_AFTER_EVALUATE;
    public static final Key QUANTITY;
    public static final Key QUERY_KEY;
    public static final Key REFERRER;
    public static final Key REFERRER_OVERRIDE;
    public static final Key REVENUE;
    public static final Key SAMPLE_RATE;
    public static final Key SEND_HITS_TO_GOOGLE;
    public static final Key SERVER_SIDE;
    public static final Key SESSION_CONTROL;
    public static final Key SESSION_COOKIE_TIMEOUT;
    public static final Key SITE_SPEED_SAMPLE_RATE;
    public static final Key SOCIAL_ACTION;
    public static final Key SOCIAL_ACTION_TARGET;
    public static final Key SOCIAL_NETWORK;
    public static final Key SOCIAL_USE_DATA_LAYER;
    public static final Key STANDARD_INDUSTRIAL_CLASSIFICATION;
    public static final Key STRIP_WWW;
    public static final Key TAG_ID;
    public static final Key TARGET_URL;
    public static final Key TIMING_CATEGORY;
    public static final Key TIMING_LABEL;
    public static final Key TIMING_SAMPLE_RATE;
    public static final Key TIMING_VALUE;
    public static final Key TIMING_VAR;
    public static final Key TITLE;
    public static final Key TRACKER_NAME;
    public static final Key TRACK_APPVIEW;
    public static final Key TRACK_DATA;
    public static final Key TRACK_EVENT;
    public static final Key TRACK_EXCEPTION;
    public static final Key TRACK_SOCIAL;
    public static final Key TRACK_TIMING;
    public static final Key TRACK_TRANSACTION;
    public static final Key TRANSACTION_DATALAYER_MAP;
    public static final Key TRANSACTION_ID;
    public static final Key TRANSACTION_ITEM_DATALAYER_MAP;
    public static final Key TRANSACTION_VARIABLE;
    public static final Key TYPE;
    public static final Key UNREPEATABLE;
    public static final Key URL;
    public static final Key USER_ID;
    public static final Key USER_VARIABLE;
    public static final Key USE_DATA_LAYER;
    public static final Key USE_HASH;
    public static final Key USE_IFRAME;
    public static final Key USE_IMAGE_TAG;
    public static final Key USE_POSTSCRIBE;
    public static final Key VALUE;
    public static final Key VALUE_IN_DOLLARS;
    public static final Key VISITOR_COOKIE_TIMEOUT;
    public static final Key WAIT_FOR_TAGS;
    public static final Key WAIT_FOR_TAGS_TIMEOUT;
    public static final Key WIDGET_IDS;
    private final String id;

    private Key(String s, int i, String s1)
    {
        super(s, i);
        id = s1;
    }

    public static Key valueOf(String s)
    {
        return (Key)Enum.valueOf(com/google/analytics/containertag/common/Key, s);
    }

    public static Key[] values()
    {
        return (Key[])$VALUES.clone();
    }

    public final String toString()
    {
        return id;
    }

    static 
    {
        ACCOUNT = new Key("ACCOUNT", 0, "account");
        ACTIVITY = new Key("ACTIVITY", 1, "activity");
        ADDITIONAL_PARAMS = new Key("ADDITIONAL_PARAMS", 2, "additional_params");
        ADVERTISER = new Key("ADVERTISER", 3, "advertiser");
        ALGORITHM = new Key("ALGORITHM", 4, "algorithm");
        ALLOW_ANCHOR = new Key("ALLOW_ANCHOR", 5, "allow_anchor");
        ALLOW_HASH = new Key("ALLOW_HASH", 6, "allow_hash");
        ALLOW_LINKER = new Key("ALLOW_LINKER", 7, "allow_linker");
        ANALYTICS_FIELDS = new Key("ANALYTICS_FIELDS", 8, "analytics_fields");
        ANALYTICS_PASS_THROUGH = new Key("ANALYTICS_PASS_THROUGH", 9, "analytics_pass_through");
        ANONYMIZE_IP = new Key("ANONYMIZE_IP", 10, "anonymize_ip");
        APP_NAME = new Key("APP_NAME", 11, "app_name");
        APP_VERSION = new Key("APP_VERSION", 12, "app_version");
        ARG0 = new Key("ARG0", 13, "arg0");
        ARG1 = new Key("ARG1", 14, "arg1");
        ATTRIBUTE = new Key("ATTRIBUTE", 15, "attribute");
        AUTO_LINK_DOMAINS = new Key("AUTO_LINK_DOMAINS", 16, "auto_link_domains");
        CACHE_BUSTER = new Key("CACHE_BUSTER", 17, "cache_buster");
        CACHE_BUSTER_VALUE = new Key("CACHE_BUSTER_VALUE", 18, "cache_buster_value");
        CAMPAIGN_CONTENT_KEY = new Key("CAMPAIGN_CONTENT_KEY", 19, "campaign_content_key");
        CAMPAIGN_CONTENT_OVERRIDE = new Key("CAMPAIGN_CONTENT_OVERRIDE", 20, "campaign_content_override");
        CAMPAIGN_COOKIE_TIMEOUT = new Key("CAMPAIGN_COOKIE_TIMEOUT", 21, "campaign_cookie_timeout");
        CAMPAIGN_MEDIUM_KEY = new Key("CAMPAIGN_MEDIUM_KEY", 22, "campaign_medium_key");
        CAMPAIGN_MEDIUM_OVERRIDE = new Key("CAMPAIGN_MEDIUM_OVERRIDE", 23, "campaign_medium_override");
        CAMPAIGN_NAME_KEY = new Key("CAMPAIGN_NAME_KEY", 24, "campaign_name_key");
        CAMPAIGN_NAME_OVERRIDE = new Key("CAMPAIGN_NAME_OVERRIDE", 25, "campaign_name_override");
        CAMPAIGN_NO_KEY = new Key("CAMPAIGN_NO_KEY", 26, "campaign_no_key");
        CAMPAIGN_SOURCE_KEY = new Key("CAMPAIGN_SOURCE_KEY", 27, "campaign_source_key");
        CAMPAIGN_SOURCE_OVERRIDE = new Key("CAMPAIGN_SOURCE_OVERRIDE", 28, "campaign_source_override");
        CAMPAIGN_TERM_KEY = new Key("CAMPAIGN_TERM_KEY", 29, "campaign_term_key");
        CAMPAIGN_TERM_OVERRIDE = new Key("CAMPAIGN_TERM_OVERRIDE", 30, "campaign_term_override");
        CAMPAIGN_TRACK = new Key("CAMPAIGN_TRACK", 31, "campaign_track");
        CATEGORY = new Key("CATEGORY", 32, "category");
        CHECK_VALIDATION = new Key("CHECK_VALIDATION", 33, "check_validation");
        CLEAR_PERSISTENT_DATA_LAYER_PREFIX = new Key("CLEAR_PERSISTENT_DATA_LAYER_PREFIX", 34, "clear_data_layer_prefix");
        CLICK_ID = new Key("CLICK_ID", 35, "click_id");
        CLIENT_INFO = new Key("CLIENT_INFO", 36, "client_info");
        COMPANY = new Key("COMPANY", 37, "company");
        COMPONENT = new Key("COMPONENT", 38, "component");
        CONTENT_DESCRIPTION = new Key("CONTENT_DESCRIPTION", 39, "content_description");
        CONTENT_GROUP = new Key("CONTENT_GROUP", 40, "content_group");
        CONVERSION_ID = new Key("CONVERSION_ID", 41, "conversion_id");
        COOKIE_DOMAIN = new Key("COOKIE_DOMAIN", 42, "cookie_domain");
        COOKIE_EXPIRATION = new Key("COOKIE_EXPIRATION", 43, "cookie_expiration");
        COOKIE_NAME = new Key("COOKIE_NAME", 44, "cookie_name");
        COOKIE_PATH = new Key("COOKIE_PATH", 45, "cookie_path");
        COOKIE_PATH_COPY = new Key("COOKIE_PATH_COPY", 46, "cookie_path_copy");
        COUNTRY = new Key("COUNTRY", 47, "country");
        CURRENCY_CODE = new Key("CURRENCY_CODE", 48, "currency_code");
        CUSTOM_VARS = new Key("CUSTOM_VARS", 49, "custom_vars");
        CUSTOMER_ID = new Key("CUSTOMER_ID", 50, "customer_id");
        DATA_LAYER_VERSION = new Key("DATA_LAYER_VERSION", 51, "data_layer_version");
        DATA_PROVIDER_ID = new Key("DATA_PROVIDER_ID", 52, "data_provider_id");
        DEBUG = new Key("DEBUG", 53, "debug");
        DECORATE_FORM = new Key("DECORATE_FORM", 54, "decorate_form");
        DECORATE_FORMS_AUTO_LINK = new Key("DECORATE_FORMS_AUTO_LINK", 55, "decorate_forms_auto_link");
        DECORATE_LINK = new Key("DECORATE_LINK", 56, "decorate_link");
        DEFAULT_PAGES = new Key("DEFAULT_PAGES", 57, "default_pages");
        DEFAULT_VALUE = new Key("DEFAULT_VALUE", 58, "default_value");
        DEPENDENCIES = new Key("DEPENDENCIES", 59, "dependencies");
        DETECT_FLASH = new Key("DETECT_FLASH", 60, "detect_flash");
        DETECT_TITLE = new Key("DETECT_TITLE", 61, "detect_title");
        DIMENSION = new Key("DIMENSION", 62, "dimension");
        DOMAIN_NAME = new Key("DOMAIN_NAME", 63, "domain_name");
        DOUBLE_CLICK = new Key("DOUBLE_CLICK", 64, "double_click");
        ECOMMERCE_MACRO_DATA = new Key("ECOMMERCE_MACRO_DATA", 65, "ecommerce_macro_data");
        ECOMMERCE_USE_DATA_LAYER = new Key("ECOMMERCE_USE_DATA_LAYER", 66, "ecommerce_use_data_layer");
        ELEMENT = new Key("ELEMENT", 67, "element");
        EMAIL = new Key("EMAIL", 68, "email");
        EMPLOYEE_RANGE = new Key("EMPLOYEE_RANGE", 69, "employee_range");
        ENABLE_ECOMMERCE = new Key("ENABLE_ECOMMERCE", 70, "enable_ecommerce");
        ESCAPE = new Key("ESCAPE", 71, "escape");
        EVENT_ACTION = new Key("EVENT_ACTION", 72, "event_action");
        EVENT_CATEGORY = new Key("EVENT_CATEGORY", 73, "event_category");
        EVENT_LABEL = new Key("EVENT_LABEL", 74, "event_label");
        EVENT_VALUE = new Key("EVENT_VALUE", 75, "event_value");
        EXCEPTION_DESCRIPTION = new Key("EXCEPTION_DESCRIPTION", 76, "exception_description");
        EXCEPTION_FATAL = new Key("EXCEPTION_FATAL", 77, "exception_fatal");
        FIELDS_TO_SET = new Key("FIELDS_TO_SET", 78, "fields_to_set");
        FORCE_SSL = new Key("FORCE_SSL", 79, "force_ssl");
        FORM_OBJECT = new Key("FORM_OBJECT", 80, "form_object");
        FUNCTION = new Key("FUNCTION", 81, "function");
        FUNCTION_CALL_NAME = new Key("FUNCTION_CALL_NAME", 82, "function_call_macro_name");
        GROUP = new Key("GROUP", 83, "group");
        GTM_ON_SUCCESS = new Key("GTM_ON_SUCCESS", 84, "gtmOnSuccess");
        GTM_ON_FAILURE = new Key("GTM_ON_FAILURE", 85, "gtmOnFailure");
        HIT_CALLBACK = new Key("HIT_CALLBACK", 86, "hit_callback");
        HTML = new Key("HTML", 87, "html");
        ID = new Key("ID", 88, "id");
        IGNORED_ORGANIC = new Key("IGNORED_ORGANIC", 89, "ignored_organic");
        IGNORED_REF = new Key("IGNORED_REF", 90, "ignored_ref");
        IGNORE_CASE = new Key("IGNORE_CASE", 91, "ignore_case");
        INPUT = new Key("INPUT", 92, "input");
        INPUT_FORMAT = new Key("INPUT_FORMAT", 93, "input_format");
        INSTANCE_NAME = new Key("INSTANCE_NAME", 94, "instance_name");
        INSTANCE_LABEL = new Key("INSTANCE_LABEL", 95, "instance_label");
        INTERVAL = new Key("INTERVAL", 96, "interval");
        ITEM_SEPARATOR = new Key("ITEM_SEPARATOR", 97, "item_separator");
        JAVASCRIPT = new Key("JAVASCRIPT", 98, "javascript");
        KEYWORD = new Key("KEYWORD", 99, "keyword");
        KEY_VALUE_SEPARATOR = new Key("KEY_VALUE_SEPARATOR", 100, "key_value_separator");
        LABEL = new Key("LABEL", 101, "label");
        LANGUAGE = new Key("LANGUAGE", 102, "language");
        LIMIT = new Key("LIMIT", 103, "limit");
        LINK = new Key("LINK", 104, "link");
        LINK_BY_POST = new Key("LINK_BY_POST", 105, "link_by_post");
        LINK_ID = new Key("LINK_ID", 106, "link_id");
        LIVE_ONLY = new Key("LIVE_ONLY", 107, "live_only");
        LOCAL_GIF_PATH = new Key("LOCAL_GIF_PATH", 108, "local_gif_path");
        LOCATION = new Key("LOCATION", 109, "location");
        MAP = new Key("MAP", 110, "map");
        MAX = new Key("MAX", 111, "max");
        MIN = new Key("MIN", 112, "min");
        METRIC = new Key("METRIC", 113, "metric");
        NAME = new Key("NAME", 114, "name");
        NAMESPACE_CODE = new Key("NAMESPACE_CODE", 115, "namespace_code");
        NAMESPACE_ID = new Key("NAMESPACE_ID", 116, "namespace_id");
        NAMESPACE_VALUE = new Key("NAMESPACE_VALUE", 117, "namespace_value");
        NONINTERACTION = new Key("NONINTERACTION", 118, "noninteraction");
        NOT_DEFAULT_MACRO = new Key("NOT_DEFAULT_MACRO", 119, "not_default_macro");
        NO_PADDING = new Key("NO_PADDING", 120, "no_padding");
        NUMBER = new Key("NUMBER", 121, "number");
        OPTOUT = new Key("OPTOUT", 122, "optout");
        ORDER = new Key("ORDER", 123, "order");
        ORDER_ID = new Key("ORDER_ID", 124, "order_id");
        ORDER_VALUE = new Key("ORDER_VALUE", 125, "order_value");
        ORDINAL = new Key("ORDINAL", 126, "ordinal");
        ORGANIC = new Key("ORGANIC", 127, "organic");
        OUTPUT_FORMAT = new Key("OUTPUT_FORMAT", 128, "output_format");
        PAGE = new Key("PAGE", 129, "page");
        PAGE_PATH = new Key("PAGE_PATH", 130, "page_path");
        PARTITION = new Key("PARTITION", 131, "partition");
        PIXEL = new Key("PIXEL", 132, "pixel");
        PLATFORM = new Key("PLATFORM", 133, "platform");
        PRICES = new Key("PRICES", 134, "prices");
        PRIORITY = new Key("PRIORITY", 135, "priority");
        PRODUCT = new Key("PRODUCT", 136, "product");
        PRODUCT_ID = new Key("PRODUCT_ID", 137, "product_id");
        PRODUCT_IDS = new Key("PRODUCT_IDS", 138, "product_ids");
        PUSH_AFTER_EVALUATE = new Key("PUSH_AFTER_EVALUATE", 139, "push_after_evaluate");
        QUANTITY = new Key("QUANTITY", 140, "quantity");
        QUERY_KEY = new Key("QUERY_KEY", 141, "query_key");
        REFERRER = new Key("REFERRER", 142, "referrer");
        REFERRER_OVERRIDE = new Key("REFERRER_OVERRIDE", 143, "referrer_override");
        REVENUE = new Key("REVENUE", 144, "revenue");
        SAMPLE_RATE = new Key("SAMPLE_RATE", 145, "sample_rate");
        SEND_HITS_TO_GOOGLE = new Key("SEND_HITS_TO_GOOGLE", 146, "send_hits_to_google");
        SESSION_CONTROL = new Key("SESSION_CONTROL", 147, "session_control");
        SESSION_COOKIE_TIMEOUT = new Key("SESSION_COOKIE_TIMEOUT", 148, "session_cookie_timeout");
        SITE_SPEED_SAMPLE_RATE = new Key("SITE_SPEED_SAMPLE_RATE", 149, "site_speed_sample_rate");
        SOCIAL_ACTION = new Key("SOCIAL_ACTION", 150, "social_action");
        SOCIAL_ACTION_TARGET = new Key("SOCIAL_ACTION_TARGET", 151, "social_action_target");
        SOCIAL_NETWORK = new Key("SOCIAL_NETWORK", 152, "social_network");
        SOCIAL_USE_DATA_LAYER = new Key("SOCIAL_USE_DATA_LAYER", 153, "social_use_data_layer");
        SERVER_SIDE = new Key("SERVER_SIDE", 154, "server_side");
        STANDARD_INDUSTRIAL_CLASSIFICATION = new Key("STANDARD_INDUSTRIAL_CLASSIFICATION", 155, "standard_industrial_classification");
        STRIP_WWW = new Key("STRIP_WWW", 156, "strip_www");
        TAG_ID = new Key("TAG_ID", 157, "tag_id");
        TARGET_URL = new Key("TARGET_URL", 158, "target_url");
        TIMING_CATEGORY = new Key("TIMING_CATEGORY", 159, "timing_category");
        TIMING_LABEL = new Key("TIMING_LABEL", 160, "timing_label");
        TIMING_SAMPLE_RATE = new Key("TIMING_SAMPLE_RATE", 161, "timing_sample_rate");
        TIMING_VALUE = new Key("TIMING_VALUE", 162, "timing_value");
        TIMING_VAR = new Key("TIMING_VAR", 163, "timing_var");
        TITLE = new Key("TITLE", 164, "title");
        TRACK_APPVIEW = new Key("TRACK_APPVIEW", 165, "track_appview");
        TRACK_DATA = new Key("TRACK_DATA", 166, "track_data");
        TRACK_EVENT = new Key("TRACK_EVENT", 167, "track_event");
        TRACK_EXCEPTION = new Key("TRACK_EXCEPTION", 168, "track_exception");
        TRACK_SOCIAL = new Key("TRACK_SOCIAL", 169, "track_social");
        TRACK_TIMING = new Key("TRACK_TIMING", 170, "track_timing");
        TRACK_TRANSACTION = new Key("TRACK_TRANSACTION", 171, "track_transaction");
        TRACKER_NAME = new Key("TRACKER_NAME", 172, "tracker_name");
        TRANSACTION_DATALAYER_MAP = new Key("TRANSACTION_DATALAYER_MAP", 173, "transaction_datalayer_map");
        TRANSACTION_ID = new Key("TRANSACTION_ID", 174, "transaction_id");
        TRANSACTION_ITEM_DATALAYER_MAP = new Key("TRANSACTION_ITEM_DATALAYER_MAP", 175, "transaction_item_datalayer_map");
        TRANSACTION_VARIABLE = new Key("TRANSACTION_VARIABLE", 176, "transaction_variable");
        TYPE = new Key("TYPE", 177, "type");
        UNREPEATABLE = new Key("UNREPEATABLE", 178, "unrepeatable");
        URL = new Key("URL", 179, "url");
        USE_DATA_LAYER = new Key("USE_DATA_LAYER", 180, "use_data_layer");
        USE_HASH = new Key("USE_HASH", 181, "use_hash");
        USE_IFRAME = new Key("USE_IFRAME", 182, "use_iframe");
        USE_IMAGE_TAG = new Key("USE_IMAGE_TAG", 183, "use_image_tag");
        USE_POSTSCRIBE = new Key("USE_POSTSCRIBE", 184, "use_postscribe");
        USER_ID = new Key("USER_ID", 185, "user_id");
        USER_VARIABLE = new Key("USER_VARIABLE", 186, "user_variable");
        VALUE = new Key("VALUE", 187, "value");
        VALUE_IN_DOLLARS = new Key("VALUE_IN_DOLLARS", 188, "value_in_dollars");
        VISITOR_COOKIE_TIMEOUT = new Key("VISITOR_COOKIE_TIMEOUT", 189, "visitor_cookie_timeout");
        WAIT_FOR_TAGS = new Key("WAIT_FOR_TAGS", 190, "wait_for_tags");
        WAIT_FOR_TAGS_TIMEOUT = new Key("WAIT_FOR_TAGS_TIMEOUT", 191, "wait_for_tags_timeout");
        WIDGET_IDS = new Key("WIDGET_IDS", 192, "widget_ids");
        Key akey[] = new Key[193];
        akey[0] = ACCOUNT;
        akey[1] = ACTIVITY;
        akey[2] = ADDITIONAL_PARAMS;
        akey[3] = ADVERTISER;
        akey[4] = ALGORITHM;
        akey[5] = ALLOW_ANCHOR;
        akey[6] = ALLOW_HASH;
        akey[7] = ALLOW_LINKER;
        akey[8] = ANALYTICS_FIELDS;
        akey[9] = ANALYTICS_PASS_THROUGH;
        akey[10] = ANONYMIZE_IP;
        akey[11] = APP_NAME;
        akey[12] = APP_VERSION;
        akey[13] = ARG0;
        akey[14] = ARG1;
        akey[15] = ATTRIBUTE;
        akey[16] = AUTO_LINK_DOMAINS;
        akey[17] = CACHE_BUSTER;
        akey[18] = CACHE_BUSTER_VALUE;
        akey[19] = CAMPAIGN_CONTENT_KEY;
        akey[20] = CAMPAIGN_CONTENT_OVERRIDE;
        akey[21] = CAMPAIGN_COOKIE_TIMEOUT;
        akey[22] = CAMPAIGN_MEDIUM_KEY;
        akey[23] = CAMPAIGN_MEDIUM_OVERRIDE;
        akey[24] = CAMPAIGN_NAME_KEY;
        akey[25] = CAMPAIGN_NAME_OVERRIDE;
        akey[26] = CAMPAIGN_NO_KEY;
        akey[27] = CAMPAIGN_SOURCE_KEY;
        akey[28] = CAMPAIGN_SOURCE_OVERRIDE;
        akey[29] = CAMPAIGN_TERM_KEY;
        akey[30] = CAMPAIGN_TERM_OVERRIDE;
        akey[31] = CAMPAIGN_TRACK;
        akey[32] = CATEGORY;
        akey[33] = CHECK_VALIDATION;
        akey[34] = CLEAR_PERSISTENT_DATA_LAYER_PREFIX;
        akey[35] = CLICK_ID;
        akey[36] = CLIENT_INFO;
        akey[37] = COMPANY;
        akey[38] = COMPONENT;
        akey[39] = CONTENT_DESCRIPTION;
        akey[40] = CONTENT_GROUP;
        akey[41] = CONVERSION_ID;
        akey[42] = COOKIE_DOMAIN;
        akey[43] = COOKIE_EXPIRATION;
        akey[44] = COOKIE_NAME;
        akey[45] = COOKIE_PATH;
        akey[46] = COOKIE_PATH_COPY;
        akey[47] = COUNTRY;
        akey[48] = CURRENCY_CODE;
        akey[49] = CUSTOM_VARS;
        akey[50] = CUSTOMER_ID;
        akey[51] = DATA_LAYER_VERSION;
        akey[52] = DATA_PROVIDER_ID;
        akey[53] = DEBUG;
        akey[54] = DECORATE_FORM;
        akey[55] = DECORATE_FORMS_AUTO_LINK;
        akey[56] = DECORATE_LINK;
        akey[57] = DEFAULT_PAGES;
        akey[58] = DEFAULT_VALUE;
        akey[59] = DEPENDENCIES;
        akey[60] = DETECT_FLASH;
        akey[61] = DETECT_TITLE;
        akey[62] = DIMENSION;
        akey[63] = DOMAIN_NAME;
        akey[64] = DOUBLE_CLICK;
        akey[65] = ECOMMERCE_MACRO_DATA;
        akey[66] = ECOMMERCE_USE_DATA_LAYER;
        akey[67] = ELEMENT;
        akey[68] = EMAIL;
        akey[69] = EMPLOYEE_RANGE;
        akey[70] = ENABLE_ECOMMERCE;
        akey[71] = ESCAPE;
        akey[72] = EVENT_ACTION;
        akey[73] = EVENT_CATEGORY;
        akey[74] = EVENT_LABEL;
        akey[75] = EVENT_VALUE;
        akey[76] = EXCEPTION_DESCRIPTION;
        akey[77] = EXCEPTION_FATAL;
        akey[78] = FIELDS_TO_SET;
        akey[79] = FORCE_SSL;
        akey[80] = FORM_OBJECT;
        akey[81] = FUNCTION;
        akey[82] = FUNCTION_CALL_NAME;
        akey[83] = GROUP;
        akey[84] = GTM_ON_SUCCESS;
        akey[85] = GTM_ON_FAILURE;
        akey[86] = HIT_CALLBACK;
        akey[87] = HTML;
        akey[88] = ID;
        akey[89] = IGNORED_ORGANIC;
        akey[90] = IGNORED_REF;
        akey[91] = IGNORE_CASE;
        akey[92] = INPUT;
        akey[93] = INPUT_FORMAT;
        akey[94] = INSTANCE_NAME;
        akey[95] = INSTANCE_LABEL;
        akey[96] = INTERVAL;
        akey[97] = ITEM_SEPARATOR;
        akey[98] = JAVASCRIPT;
        akey[99] = KEYWORD;
        akey[100] = KEY_VALUE_SEPARATOR;
        akey[101] = LABEL;
        akey[102] = LANGUAGE;
        akey[103] = LIMIT;
        akey[104] = LINK;
        akey[105] = LINK_BY_POST;
        akey[106] = LINK_ID;
        akey[107] = LIVE_ONLY;
        akey[108] = LOCAL_GIF_PATH;
        akey[109] = LOCATION;
        akey[110] = MAP;
        akey[111] = MAX;
        akey[112] = MIN;
        akey[113] = METRIC;
        akey[114] = NAME;
        akey[115] = NAMESPACE_CODE;
        akey[116] = NAMESPACE_ID;
        akey[117] = NAMESPACE_VALUE;
        akey[118] = NONINTERACTION;
        akey[119] = NOT_DEFAULT_MACRO;
        akey[120] = NO_PADDING;
        akey[121] = NUMBER;
        akey[122] = OPTOUT;
        akey[123] = ORDER;
        akey[124] = ORDER_ID;
        akey[125] = ORDER_VALUE;
        akey[126] = ORDINAL;
        akey[127] = ORGANIC;
        akey[128] = OUTPUT_FORMAT;
        akey[129] = PAGE;
        akey[130] = PAGE_PATH;
        akey[131] = PARTITION;
        akey[132] = PIXEL;
        akey[133] = PLATFORM;
        akey[134] = PRICES;
        akey[135] = PRIORITY;
        akey[136] = PRODUCT;
        akey[137] = PRODUCT_ID;
        akey[138] = PRODUCT_IDS;
        akey[139] = PUSH_AFTER_EVALUATE;
        akey[140] = QUANTITY;
        akey[141] = QUERY_KEY;
        akey[142] = REFERRER;
        akey[143] = REFERRER_OVERRIDE;
        akey[144] = REVENUE;
        akey[145] = SAMPLE_RATE;
        akey[146] = SEND_HITS_TO_GOOGLE;
        akey[147] = SESSION_CONTROL;
        akey[148] = SESSION_COOKIE_TIMEOUT;
        akey[149] = SITE_SPEED_SAMPLE_RATE;
        akey[150] = SOCIAL_ACTION;
        akey[151] = SOCIAL_ACTION_TARGET;
        akey[152] = SOCIAL_NETWORK;
        akey[153] = SOCIAL_USE_DATA_LAYER;
        akey[154] = SERVER_SIDE;
        akey[155] = STANDARD_INDUSTRIAL_CLASSIFICATION;
        akey[156] = STRIP_WWW;
        akey[157] = TAG_ID;
        akey[158] = TARGET_URL;
        akey[159] = TIMING_CATEGORY;
        akey[160] = TIMING_LABEL;
        akey[161] = TIMING_SAMPLE_RATE;
        akey[162] = TIMING_VALUE;
        akey[163] = TIMING_VAR;
        akey[164] = TITLE;
        akey[165] = TRACK_APPVIEW;
        akey[166] = TRACK_DATA;
        akey[167] = TRACK_EVENT;
        akey[168] = TRACK_EXCEPTION;
        akey[169] = TRACK_SOCIAL;
        akey[170] = TRACK_TIMING;
        akey[171] = TRACK_TRANSACTION;
        akey[172] = TRACKER_NAME;
        akey[173] = TRANSACTION_DATALAYER_MAP;
        akey[174] = TRANSACTION_ID;
        akey[175] = TRANSACTION_ITEM_DATALAYER_MAP;
        akey[176] = TRANSACTION_VARIABLE;
        akey[177] = TYPE;
        akey[178] = UNREPEATABLE;
        akey[179] = URL;
        akey[180] = USE_DATA_LAYER;
        akey[181] = USE_HASH;
        akey[182] = USE_IFRAME;
        akey[183] = USE_IMAGE_TAG;
        akey[184] = USE_POSTSCRIBE;
        akey[185] = USER_ID;
        akey[186] = USER_VARIABLE;
        akey[187] = VALUE;
        akey[188] = VALUE_IN_DOLLARS;
        akey[189] = VISITOR_COOKIE_TIMEOUT;
        akey[190] = WAIT_FOR_TAGS;
        akey[191] = WAIT_FOR_TAGS_TIMEOUT;
        akey[192] = WIDGET_IDS;
        $VALUES = akey;
    }
}
